# Environment URL's
duckGoUrl=https://duckduckgo.com/
herokuCheckboxesUrl=https://the-internet.herokuapp.com/checkboxes
herokuUploadUrl=https://the-internet.herokuapp.com/upload
w3schoolsUrl=https://www.w3schools.com/html/html_tables.asp
jqueryUrl=https://jqueryui.com/resources/demos/droppable/default.html